jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Install dependencies (Debugging)
        run: |
          echo "Checking dependencies..."
          pip install --no-cache-dir -r requirements.txt --verbose

      - name: Build Docker Image
        run: docker build --no-cache --progress=plain -t fressrg/trial1 .
